apiVersion: v1
kind: Service
metadata:
  name: spring-service
  namespace: sample
  labels: 
    app: spring
spec:
  type: LoadBalancer
  ports:
  - name: port-9999
    port: 8080
    protocol: TCP
  selector:
    app: spring