apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-deployment
  namespace: sample
  labels: 
    app: spring
spec: 
  replicas: 4
  revisionHistoryLimit: 2
  selector: 
    matchLabels:
      app: spring
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata: 
      labels:
        app: spring
    spec:
      containers:
      - name: spring-con
        image: prod-sample-project
        ports: 
          - name: port-8080
            protocol: TCP
            containerPort: 8080
        env: 
         - run: test
        envFrom:
        - configMapRef:
            name: spring-config
